-- No database required — this is a static portfolio site.
-- Contact form submissions are handled by Vercel serverless function (api/send-email.ts) via Resend, owned by Email Agent.
-- Supabase is reserved for potential future use; no tables, RLS, or storage buckets are provisioned at launch.