-- No database required — contact form handled by Email Agent via Vercel serverless function.
-- Static site with no user-generated data storage. Supabase used only for potential future features.
-- Table prefix reserved: app_7660_